### ISSUE TITLE
Gitについて

### ISSUE THREAD

**Issue by r-ralph** [mspjp/20170311-handson-osaka#2]
WindowsにGitを入れるとき、Git for Windows（https://git-for-windows.github.io/）だと何故か自分の環境ではインストーラーが途中で応答をなくしてしまう現象が出ていたので念のため注意しておいていただければと
Windows7時代のときはならなかったので、もしかしたら10のみの可能性？
下手にインストールさせるよりはSourceTreeなどの内蔵Gitがある方がPathの問題も含めて便利かもしれません

**Comment by garicchi** [comment]
インストールできなかった場合はsource treeをインストールしてくださいって追記しますね

**Comment by r-ralph** [comment]
:bow:
